---
title: "cluster_maker"
author: "Julia Gustavsen"
date: "June 23, 2016"
output: 
    html_document:
      keep_md: true
      number_sections: yes
      theme: cerulean
      toc: yes
      toc_depth: 6 
---

```{r, message = FALSE}
library(RCy3)
library(httr)
library(RJSONIO)
source("./functions_to_add_to_RCy3/working_with_namespaces.R")
```

# Trying out clusterMaker with R 
```{r}
cy <- CytoscapeConnection ()
getCommandsWithinNamespace(cy, "cluster")
```

Following this tutorial: 

http://opentutorials.cgl.ucsf.edu/index.php/Tutorial:Cluster_Maker

# Read in provided session file (.cys file)
```{r}
command.name <- "open"

request.uri <- paste(cy@uri,
                     pluginVersion(cy),
                     "commands/session",
                     as.character(command.name),
                     sep = "/")
## load session
properties.list <- list(file="/home/julia_g/windows_school/gsoc/gsoc_Rcy3_vignettes/data/GalFiltered.cys")
request.res <- GET(url = request.uri,
                   query = properties.list)

getWindowList(cy)

connect_window_to_R_session <- existing.CytoscapeWindow("galFiltered.sif",                                                                      copy.graph.from.cytoscape.to.R = FALSE)
```

Graph from session is loaded into Cytoscape

```{r}
getCommandsWithinNamespace(connect_window_to_R_session, "cluster/hierarchical")
```


```{r}
node_list <- list("gal1RGexp",
                  "gal4RGexp",
                  "gal80Rexp")

properties.list <- list(nodeAttributeList = node_list[[1]],
                        nodeAttributeList = node_list[[2]],
                        nodeAttributeList = node_list[[3]],
                        network = connect_window_to_R_session@title,
                        selectedOnly = FALSE,
                        clusterAttributes = FALSE,
                        ignoreMissing = FALSE,
                        createGroups = TRUE,
                        showUI = FALSE)

command.name <- "hierarchical"
request.uri <- paste(connect_window_to_R_session@uri,
                     pluginVersion(cy),
                     "commands/cluster",
                     as.character(command.name),
                     sep = "/")

request.res <- GET(url = request.uri,
                   query = properties.list,
                   verbose())
request.res$url
http_status(request.res)
request.res$status_code
```

# Stuck here. Cannot get this to work. 

- Cannot see clustermaker window in Cytoscape
